name: boton_cosib
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.0.0 # Dependencia para manejar las solicitudes HTTP
  json_annotation: ^4.8.0 # Manejo de la serialización/deserialización JSON
  openapi_generator_annotations: ^4.11.0 # Anotaciones necesarias para la generación de código OpenAPI
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  build_runner: ^2.4.0 # Herramienta para generar código adicional
  json_serializable: ^6.7.0 # Generador de código para la serialización JSON
  openapi_generator: ^4.11.0 # Generador de código OpenAPI
  boton_api:
    path: boton_api
  geolocator: ^13.0.1
  uuid: ^4.5.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  video_player: ^2.9.1
  path_provider: ^2.1.4
  cross_file: ^0.3.4+2
  web_socket_channel: ^3.0.1
  flutter_image_compress: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0 # Herramienta para generar código adicional
  json_serializable: ^6.7.0 # Generador de código para la serialización JSON
  openapi_generator: ^4.11.0 # Generador de código OpenAPI

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
    - .env
    - assets/logo1.png
    - assets/logo2.png
